apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-deploy-test
description: cloud deploy delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
#  - targetId: qa
 - targetId: stage
 - targetId: prod
 
---
 
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev cluster
requireApproval: false
gke:
  cluster: projects/one-dev-345702/locations/asia-northeast1-a/clusters/one-dev-cluster1
 
---
 
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/one-dev-345702/locations/asia-northeast1-a/clusters/one-dev-cluster1
 
# ---
 
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: qa
# description: qa cluster
# requireApproval: true
# gke:
#   cluster: projects/one-dev-345702/locations/asia-northeast1-a/clusters/one-dev-cluster1
 
---
 
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stage
description: stage cluster
requireApproval: true
gke:
  cluster: projects/one-dev-345702/locations/asia-northeast1-a/clusters/one-dev-cluster1